export const bg = {
  metadata: { home: { title: "SIMO | Digital Craftsman – Изработка на уебсайтове и онлайн магазини", description: "Изработка на модерни уебсайтове, онлайн магазини и custom дигитални решения с WordPress, Shopify, CloudCart и съвременни технологии." } },
  navigation: { label: "Основна навигация", home: "Начало", services: "Услуги", pricing: "Цени", projects: "Проекти", about: "За мен", contact: "Контакти", openMenu: "Отвори менюто", closeMenu: "Затвори менюто", expandMenu: "Разгъни навигацията", collapseMenu: "Свий навигацията", callMe: "Обади ми се", changeLanguage: "Смени езика", startProject: "Започни проект", skipToContent: "Към основното съдържание" },
  hero: { kickerDesign: "Уеб дизайн", kickerSeparator: "•", kickerCommerce: "E-commerce", kickerSeo: "SEO", titleLineOne: "Твоят дигитален", titleLineTwo: "майстор", descriptionLineOne: "Модерен дизайн, чист код и ясна структура", descriptionLineTwo: "за твоя бизнес.", scrollPrompt: "Скролни", scrollLabel: "Превърти надолу" },
  servicesShowcase: { sectionNumber: "01", eyebrow: "Услуги", titleLineOne: "От идея до работещ", titleLineTwo: "дигитален продукт.", description: "Дизайн, разработка и поддръжка, събрани в един ясен процес.", listLabel: "Услуги", enquireAbout: "Запитване за {service}", ctaPrompt: "Не си сигурен от какво имаш нужда?", ctaLabel: "Разкажи ми за проекта" },
  projectsShowcase: { sectionNumber: "02", eyebrow: "Избрани проекти", titleLineOne: "Работа, която", titleLineTwo: "говори сама.", description: "Подбрани проекти и примерна структура за бъдещите case study страници.", openProject: "Разгледай {project}", viewProject: "Виж проекта", sampleLabel: "Примерен запис", allProjects: "Разгледай всички проекти" },
  processShowcase: { sectionNumber: "03", eyebrow: "Процес", titleLineOne: "Ясен път от", titleLineTwo: "идея до развитие.", description: "Всяка стъпка има конкретна цел, ясен резултат и логично място в процеса." },
  aboutShowcase: { sectionNumber: "04", eyebrow: "За мен", titleLineOne: "Човекът зад", titleLineTwo: "SIMO.", description: "Аз съм Симо — дизайнер и разработчик, който съчетава ясна визуална посока с чиста техническа реализация.", supporting: "Фокусът ми е върху структурата, вниманието към детайла и дигиталните решения, които са лесни за използване и поддръжка.", focusLabel: "Основни направления", focusDesign: "Дизайн", focusDevelopment: "Разработка", focusSupport: "Поддръжка", ctaLabel: "Нека работим заедно", portraitAlt: "Портрет на Симо" },
  technologiesShowcase: { sectionNumber: "05", eyebrow: "Технологии", title: "Инструментите зад работата." },
  faqShowcase: { sectionNumber: "06", eyebrow: "Въпроси и отговори", titleLineOne: "Преди да", titleLineTwo: "започнем.", description: "Кратки отговори на най-честите въпроси преди началото на един проект." },
  contactShowcase: { sectionNumber: "07", eyebrow: "Контакт", titleLineOne: "Имаш идея?", titleLineTwo: "Да я направим.", description: "Разкажи ми накратко за проекта и ще подредим най-подходящите следващи стъпки.", formTitle: "Разкажи ми за проекта", requiredHint: "Полетата със * са задължителни.", nameLabel: "Име", namePlaceholder: "Твоето име", emailLabel: "Имейл", emailPlaceholder: "name@example.com", phoneLabel: "Телефон", optional: "по желание", phonePlaceholder: "+359…", serviceLabel: "От какво имаш нужда?", servicePlaceholder: "Избери услуга", serviceOther: "Друго / Не съм сигурен", messageLabel: "За проекта", messagePlaceholder: "Каква е идеята, целта и текущото състояние?", submit: "Изпрати запитване", sending: "Изпращане…", successTitle: "Запитването е изпратено.", successMessage: "Благодаря! Ще се свържа с теб, за да обсъдим следващите стъпки.", errorMessage: "Запитването не беше изпратено. Опитай отново или използвай телефона за контакт.", privacyNote: "С изпращането потвърждаваш, че си прочел/а", privacyLink: "Политиката за поверителност" },
  footer: { navigationLabel: "Навигация във footer-а", socialLabel: "Социални мрежи", privacy: "Поверителност и защита на данните", backToTop: "Обратно нагоре", rights: "Всички права запазени." },
  privacy: { eyebrow: "Правна информация", title: "Поверителност и защита на данните", intro: "Тази политика обяснява какви данни се събират чрез сайта, защо са необходими и как можеш да упражниш правата си.", updatedLabel: "Последна актуализация", updatedValue: "22 юли 2026 г.", contactLabel: "Контакт с администратора", authorityLabel: "Комисия за защита на личните данни", backHome: "Към началната страница" },
  projectDetail: { backToProjects: "Към всички проекти", sampleLabel: "Примерен проект", overview: "За проекта", technologies: "Технологии", projectFacts: "Детайли", year: "Година", projectType: "Тип проект", support: "Статус", ongoingSupport: "Текуща поддръжка", testimonial: "Думи от клиента", visitWebsite: "Посети уебсайта", nextProject: "Следващ проект", pendingTitle: "Case study съдържанието предстои.", pendingDescription: "Името, описанието, изображенията и детайлите ще бъдат добавени след потвърждение." },
  pricingPage: {
    metadata: { title: "Цени за уебсайтове и онлайн магазини | SIMO", description: "Пакети и цени за бизнес уебсайтове, онлайн магазини, поддръжка и дигитален маркетинг от SIMO | Digital Craftsman." },
    eyebrow: "Ценоразпис 2026", titleLineOne: "Ясни цени.", titleLineTwo: "Без изненади.", description: "Избери ясна начална рамка. След кратък разговор ще потвърдим точния обхват и най-подходящото решение за проекта.", cta: "Обсъди проекта",
    plansEyebrow: "Пакети", plansTitle: "Основа за силно онлайн присъствие.", popular: "Най-популярен", oneTime: "еднократно за изработка", support: "Поддръжка", perMonth: "/месец", firstMonth: "Първи месец маркетинг настройка", free: "Безплатно", afterFirstMonth: "След това:", choosePlan: "Избери пакет",
    marketingEyebrow: "Допълнителна услуга", marketingTitle: "Marketing Care", important: "Важно:", adBudgetNote: "Рекламният бюджет за платени кампании не е включен и се заплаща отделно от клиента.",
    supportEyebrow: "Поддръжка", supportTitle: "Сайтът остава в добри ръце.",
    installmentsEyebrow: "Плащане", installmentsTitle: "Гъвкаво разсрочване.", installmentsDescription: "Краткосрочно плащане на вноски с 8% административна такса върху пакетната цена.", cash: "Наведнъж", installmentTotal: "Обща сума при разсрочване", installmentNote: "Разсрочването може да бъде седмично, двуседмично или месечно. Конкретният график се потвърждава преди старта.",
    finalEyebrow: "Следващата стъпка", finalTitle: "Кажи ми какво искаш да изградим.", finalDescription: "Ще прегледаме целите, съдържанието и нужните функционалности, преди да потвърдим финалната оферта."
  },
  common: { externalLink: "Отваря се в нов раздел", loading: "Зареждане…", errorTitle: "Нещо се обърка", errorAction: "Опитай отново", notFoundTitle: "Страницата не е намерена", notFoundAction: "Към началото", stageNotice: "Тази страница ще бъде изградена в следващ етап." },
} as const;
type WidenStrings<T> = { [Key in keyof T]: T[Key] extends string ? string : WidenStrings<T[Key]> };
export type Dictionary = WidenStrings<typeof bg>;
