import type { Dictionary } from "./bg";
export const en = {
  metadata: { home: { title: "SIMO | Digital Craftsman – Websites and E-commerce Development", description: "Modern websites, online stores and custom digital solutions built with WordPress, Shopify, CloudCart and modern web technologies." } },
  navigation: { label: "Primary navigation", home: "Home", services: "Services", pricing: "Pricing", projects: "Projects", about: "About", contact: "Contact", openMenu: "Open menu", closeMenu: "Close menu", expandMenu: "Expand navigation", collapseMenu: "Collapse navigation", callMe: "Call me", changeLanguage: "Change language", startProject: "Start a project", skipToContent: "Skip to main content" },
  hero: { kickerDesign: "Web design", kickerSeparator: "•", kickerCommerce: "E-commerce", kickerSeo: "SEO", titleLineOne: "Your Digital", titleLineTwo: "Craftsman", descriptionLineOne: "Modern design, clean code and clear structure", descriptionLineTwo: "for your business.", scrollPrompt: "Scroll", scrollLabel: "Scroll down" },
  servicesShowcase: { sectionNumber: "01", eyebrow: "Services", titleLineOne: "From an idea to a working", titleLineTwo: "digital product.", description: "Design, development and support brought together in one clear process.", listLabel: "Services", enquireAbout: "Enquire about {service}", ctaPrompt: "Not sure what you need?", ctaLabel: "Tell me about your project" },
  projectsShowcase: { sectionNumber: "02", eyebrow: "Selected projects", titleLineOne: "Work that", titleLineTwo: "speaks for itself.", description: "Selected projects and a sample structure for the future case study pages.", openProject: "View {project}", viewProject: "View project", sampleLabel: "Sample entry", allProjects: "View all projects" },
  processShowcase: { sectionNumber: "03", eyebrow: "Process", titleLineOne: "A clear path from", titleLineTwo: "idea to growth.", description: "Every step has a specific purpose, a clear outcome and a logical place in the process." },
  aboutShowcase: { sectionNumber: "04", eyebrow: "About me", titleLineOne: "The person behind", titleLineTwo: "SIMO.", description: "I am Simo — a designer and developer combining a clear visual direction with clean technical execution.", supporting: "My focus is on structure, attention to detail and digital solutions that are easy to use and maintain.", focusLabel: "Core disciplines", focusDesign: "Design", focusDevelopment: "Development", focusSupport: "Support", ctaLabel: "Let’s work together", portraitAlt: "Portrait of Simo" },
  technologiesShowcase: { sectionNumber: "05", eyebrow: "Technologies", title: "The tools behind the work." },
  faqShowcase: { sectionNumber: "06", eyebrow: "Questions and answers", titleLineOne: "Before we", titleLineTwo: "get started.", description: "Short answers to the most common questions before starting a project." },
  contactShowcase: { sectionNumber: "07", eyebrow: "Contact", titleLineOne: "Have an idea?", titleLineTwo: "Let’s build it.", description: "Tell me briefly about your project and we will organise the most suitable next steps.", formTitle: "Tell me about your project", requiredHint: "Fields marked with * are required.", nameLabel: "Name", namePlaceholder: "Your name", emailLabel: "Email", emailPlaceholder: "name@example.com", phoneLabel: "Phone", optional: "optional", phonePlaceholder: "+44…", serviceLabel: "What do you need?", servicePlaceholder: "Choose a service", serviceOther: "Other / Not sure yet", messageLabel: "About the project", messagePlaceholder: "What is the idea, goal and current state?", submit: "Send enquiry", sending: "Sending…", successTitle: "Your enquiry has been sent.", successMessage: "Thank you! I will get in touch to discuss the next steps.", errorMessage: "Your enquiry could not be sent. Try again or use the contact phone number.", privacyNote: "By sending this form, you confirm that you have read the", privacyLink: "Privacy Policy" },
  footer: { navigationLabel: "Footer navigation", socialLabel: "Social media", privacy: "Privacy and data protection", backToTop: "Back to top", rights: "All rights reserved." },
  privacy: { eyebrow: "Legal information", title: "Privacy and data protection", intro: "This policy explains what data is collected through the website, why it is needed and how you can exercise your rights.", updatedLabel: "Last updated", updatedValue: "22 July 2026", contactLabel: "Contact the controller", authorityLabel: "Bulgarian Commission for Personal Data Protection", backHome: "Back to the home page" },
  projectDetail: { backToProjects: "Back to all projects", sampleLabel: "Sample project", overview: "Project overview", technologies: "Technologies", projectFacts: "Details", year: "Year", projectType: "Project type", support: "Status", ongoingSupport: "Ongoing support", testimonial: "Client testimonial", visitWebsite: "Visit website", nextProject: "Next project", pendingTitle: "Case study content is coming next.", pendingDescription: "The name, copy, images and project details will be added after confirmation." },
  pricingPage: {
    metadata: { title: "Website and online store pricing | SIMO", description: "Packages and pricing for business websites, online stores, maintenance and digital marketing by SIMO | Digital Craftsman." },
    eyebrow: "Pricing 2026", titleLineOne: "Clear pricing.", titleLineTwo: "No surprises.", description: "Choose a clear starting point. After a short conversation, we will confirm the exact scope and the right solution for your project.", cta: "Discuss your project",
    plansEyebrow: "Packages", plansTitle: "A strong foundation for your online presence.", popular: "Most popular", oneTime: "one-off build fee", support: "Support", perMonth: "/month", firstMonth: "First month marketing setup", free: "Free", afterFirstMonth: "Afterwards:", choosePlan: "Choose package",
    marketingEyebrow: "Additional service", marketingTitle: "Marketing Care", important: "Important:", adBudgetNote: "The advertising budget for paid campaigns is not included and is paid separately by the client.",
    supportEyebrow: "Support", supportTitle: "Your website stays in good hands.",
    installmentsEyebrow: "Payment", installmentsTitle: "Flexible instalments.", installmentsDescription: "Short-term instalments with an 8% administration fee applied to the package price.", cash: "Paid in full", installmentTotal: "Total with instalments", installmentNote: "Instalments can be weekly, fortnightly or monthly. The exact schedule is confirmed before the project begins.",
    finalEyebrow: "The next step", finalTitle: "Tell me what you want to build.", finalDescription: "We will review the goals, content and required functionality before confirming the final proposal."
  },
  common: { externalLink: "Opens in a new tab", loading: "Loading…", errorTitle: "Something went wrong", errorAction: "Try again", notFoundTitle: "Page not found", notFoundAction: "Back home", stageNotice: "This page will be built in a later stage." },
} satisfies Dictionary;
